stages:
- name: Build
  steps:
  - runScriptConfig:
      image: chengjianqiang/maven:3-j7-cached-2
      shellScript: |-
        mvn clean install
        echo aaa
        ls
        pwd
        echo aaa
  - runScriptConfig:
      image: java:8
      shellScript: |
        echo bbb
        ls
    when:
      branch: {}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: chengjianqiang/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      DOCKER_HOST: tcp://docker-dind.default:2375
      PLUGIN_DEAMON_OFF: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  - applyAppConfig:
      catalogTemplate: p-vzxmh:pipeline-chart-demo
      version: 0.1.0
      answers:
        image.tag: ${CICD_EXECUTION_SEQUENCE}
      name: pipeline-app
      targetNamespace: pipeline
  - runScriptConfig:
      image: roffe/kubectl
      shellScript: kubectl  create deployment demo-$RANDOM  --image=nginx -n pipeline
timeout: 20
branch: {}
notification: {}
