stages:
- name: Build
  steps:
  - runScriptConfig:
      image: chengjianqiang/maven:3-j7-cached-2
      shellScript: |-
        mvn clean install
        echo aaa
        ls
        pwd
        echo aaa
  - runScriptConfig:
      image: java:8
      shellScript: |
        echo bbb
        ls
    when:
      branch: {}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: chengjianqiang/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 20
branch: {}
notification: {}
