stages:
- name: Build
  steps:
  - runScriptConfig:
      image: lawr/maven:3-jdk-7
      shellScript: |-
        mvn clean install
        echo aaa
        ls
        pwd
        echo aaa
  - runScriptConfig:
      image: java:8
      shellScript: |
        echo bbb
        ls
    when:
      branch: {}
  - runScriptConfig:
      image: chengjianqiang/maven:3-j7-cached
      shellScript: |+
        ls
        pwd

- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
  - runScriptConfig:
      image: java:8
      shellScript: |-
        echo ccc
        ls
        pwd
        echo ccc
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 20
branch: {}
notification: {}
